# To open in separate terminal:
# docker exec -it reppy-backend-1 /bin/bash
# tmux

version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    volumes:
     - ./backend:/app
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=db
      - DB_USER=user01
      - DB_PASSWORD=user01239nTGN35pio!
      - DB_NAME=reppydb
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    volumes:
      # copy init scripts from local init/ into PSQL's special init dir
      - ./backend/internal/database/init:/docker-entrypoint-initdb.d
      # persist data here, even if container restarts or gets rm'd
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user01
      - POSTGRES_PASSWORD=user01239nTGN35pio!
      - POSTGRES_DB=reppydb
    ports:
      - "8082:5432" #8082:5432 is for connecting to Postgres from outside Docker, e.g. using a db client on host machine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user01 -d reppydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@test.com
      - PGADMIN_DEFAULT_PASSWORD=123lng@#N5las
    ports:
      - "8083:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db

volumes:
  postgres_data: